baseURL = 'https://www.pqcryp.top/'
languageCode = 'en-us'
title = '认真写点东西的地方'
theme = "etch"

[params]
description = "lkcp's blog"
dark = "auto"
copyright = "Copyright © 2024 lkcp"
highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true